"""empty message

Revision ID: 65405f8c54d3
Revises: 2b8938063306
Create Date: 2018-11-20 09:55:37.983896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65405f8c54d3'
down_revision = '2b8938063306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_delete')
    op.drop_column('user', 'is_active')
    op.create_table('axf_orderitem',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('buy_money', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('goods_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['goods_id'], ['axf_goods.id'], name='axf_orderitem_goods_id_49627d3f_fk_axf_goods_id'),
    sa.ForeignKeyConstraint(['order_id'], ['axf_order.id'], name='axf_orderitem_order_id_f5b41669_fk_axf_order_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('axf_myuser_user_permissions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('myuser_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['myuser_id'], ['axf_myuser.id'], name='axf_myuser_user_permissions_myuser_id_bb752342_fk_axf_myuser_id'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='axf_myuser_user_perm_permission_id_5633aa56_fk_auth_perm'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('axf_myuser_user_permissi_myuser_id_permission_id_8b1e4ace_uniq', 'axf_myuser_user_permissions', ['myuser_id', 'permission_id'], unique=True)
    op.create_table('axf_myuser_groups',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('myuser_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='axf_myuser_groups_group_id_0016cded_fk_auth_group_id'),
    sa.ForeignKeyConstraint(['myuser_id'], ['axf_myuser.id'], name='axf_myuser_groups_myuser_id_e392929b_fk_axf_myuser_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('axf_myuser_groups_myuser_id_group_id_ea7e3206_uniq', 'axf_myuser_groups', ['myuser_id', 'group_id'], unique=True)
    op.create_table('axf_foodtypes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('typeid', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('typename', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('childtypenames', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('typesort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('django_migrations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('app', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('applied', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('django_content_type',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('app_label', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('django_content_type_app_label_model_76bd3d3b_uniq', 'django_content_type', ['app_label', 'model'], unique=True)
    op.create_table('auth_group_permissions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('auth_group_permissions_group_id_permission_id_0cd325b0_uniq', 'auth_group_permissions', ['group_id', 'permission_id'], unique=True)
    op.create_table('axf_goods',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('productid', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('productimg', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('productname', mysql.VARCHAR(length=130), nullable=False),
    sa.Column('productlongname', mysql.VARCHAR(length=190), nullable=False),
    sa.Column('isxf', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('pmdesc', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('specifics', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('marketprice', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('categoryid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('childcid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('childcidname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('dealerid', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('storenums', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('productnum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('djcelery_periodictasks',
    sa.Column('ident', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('last_update', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('ident'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_group',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'auth_group', ['name'], unique=True)
    op.create_table('axf_minebtns',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('btn', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('class_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('bref_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('celery_taskmeta',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('task_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('result', mysql.LONGTEXT(), nullable=True),
    sa.Column('date_done', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('traceback', mysql.LONGTEXT(), nullable=True),
    sa.Column('hidden', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('meta', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('task_id', 'celery_taskmeta', ['task_id'], unique=True)
    op.create_index('celery_taskmeta_hidden_23fd02dc', 'celery_taskmeta', ['hidden'], unique=False)
    op.create_table('axf_myuser',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('last_login', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('date_joined', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=251), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=13), nullable=True),
    sa.Column('icon', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'axf_myuser', ['username'], unique=True)
    op.create_index('email', 'axf_myuser', ['email'], unique=True)
    op.create_table('axf_wheel',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('img', mysql.VARCHAR(length=251), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('trackid', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('django_admin_log',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('action_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('object_id', mysql.LONGTEXT(), nullable=True),
    sa.Column('object_repr', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('action_flag', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('change_message', mysql.LONGTEXT(), nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co'),
    sa.ForeignKeyConstraint(['user_id'], ['axf_myuser.id'], name='django_admin_log_user_id_c564eba6_fk_axf_myuser_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('djcelery_crontabschedule',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('minute', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('hour', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('day_of_week', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('day_of_month', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('month_of_year', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('djcelery_periodictask',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('task', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('args', mysql.LONGTEXT(), nullable=False),
    sa.Column('kwargs', mysql.LONGTEXT(), nullable=False),
    sa.Column('queue', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('exchange', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('routing_key', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('expires', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('last_run_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('total_run_count', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('date_changed', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('description', mysql.LONGTEXT(), nullable=False),
    sa.Column('crontab_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('interval_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crontab_id'], ['djcelery_crontabschedule.id'], name='djcelery_periodictas_crontab_id_75609bab_fk_djcelery_'),
    sa.ForeignKeyConstraint(['interval_id'], ['djcelery_intervalschedule.id'], name='djcelery_periodictas_interval_id_b426ab02_fk_djcelery_'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'djcelery_periodictask', ['name'], unique=True)
    op.create_table('djcelery_workerstate',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('hostname', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('last_heartbeat', mysql.DATETIME(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('hostname', 'djcelery_workerstate', ['hostname'], unique=True)
    op.create_index('djcelery_workerstate_last_heartbeat_4539b544', 'djcelery_workerstate', ['last_heartbeat'], unique=False)
    op.create_table('axf_shop',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('img', mysql.VARCHAR(length=251), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('trackid', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('djcelery_intervalschedule',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('every', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('period', mysql.VARCHAR(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('axf_mainshow',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('img', mysql.VARCHAR(length=251), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('trackid', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('categoryid', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('brandname', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('img1', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('childcid1', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('productid1', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('longname1', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('price1', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('marketprice1', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('img2', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('childcid2', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('productid2', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('longname2', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('price2', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('marketprice2', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('img3', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('childcid3', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('productid3', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('longname3', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('price3', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('marketprice3', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('axf_nav',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('img', mysql.VARCHAR(length=251), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('trackid', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('axf_mustbuy',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('img', mysql.VARCHAR(length=251), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('trackid', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('django_session',
    sa.Column('session_key', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('session_data', mysql.LONGTEXT(), nullable=False),
    sa.Column('expire_date', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('session_key'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('django_session_expire_date_a5c62663', 'django_session', ['expire_date'], unique=False)
    op.create_table('celery_tasksetmeta',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('taskset_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('result', mysql.LONGTEXT(), nullable=False),
    sa.Column('date_done', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('hidden', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('taskset_id', 'celery_tasksetmeta', ['taskset_id'], unique=True)
    op.create_index('celery_tasksetmeta_hidden_593cfc24', 'celery_tasksetmeta', ['hidden'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('codename', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('auth_permission_content_type_id_codename_01ab375a_uniq', 'auth_permission', ['content_type_id', 'codename'], unique=True)
    op.create_table('axf_cart',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('is_selected', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('goods_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['goods_id'], ['axf_goods.id'], name='axf_cart_goods_id_46fdd1df_fk_axf_goods_id'),
    sa.ForeignKeyConstraint(['user_id'], ['axf_myuser.id'], name='axf_cart_user_id_439bbb3d_fk_axf_myuser_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('axf_cart_user_id_goods_id_747867f1_idx', 'axf_cart', ['user_id', 'goods_id'], unique=False)
    op.create_table('djcelery_taskstate',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('state', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('task_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('tstamp', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('args', mysql.LONGTEXT(), nullable=True),
    sa.Column('kwargs', mysql.LONGTEXT(), nullable=True),
    sa.Column('eta', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('expires', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('result', mysql.LONGTEXT(), nullable=True),
    sa.Column('traceback', mysql.LONGTEXT(), nullable=True),
    sa.Column('runtime', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('retries', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('hidden', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('worker_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['djcelery_workerstate.id'], name='djcelery_taskstate_worker_id_f7f57a05_fk_djcelery_workerstate_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('task_id', 'djcelery_taskstate', ['task_id'], unique=True)
    op.create_index('djcelery_taskstate_tstamp_4c3f93a1', 'djcelery_taskstate', ['tstamp'], unique=False)
    op.create_index('djcelery_taskstate_state_53543be4', 'djcelery_taskstate', ['state'], unique=False)
    op.create_index('djcelery_taskstate_name_8af9eded', 'djcelery_taskstate', ['name'], unique=False)
    op.create_index('djcelery_taskstate_hidden_c3905e57', 'djcelery_taskstate', ['hidden'], unique=False)
    op.create_table('axf_order',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['axf_myuser.id'], name='axf_order_user_id_65d915f1_fk_axf_myuser_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
